version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 10
    reviewers:
      - "Rustamiqq"
    assignees:
      - "Rustamiqq"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
      - "automated"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
    # Group minor and patch updates together
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 5
    reviewers:
      - "Rustamiqq"
    assignees:
      - "Rustamiqq"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "ci"
      - "automated"

  # Enable version updates for Docker (if applicable)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 3
    reviewers:
      - "Rustamiqq"
    assignees:
      - "Rustamiqq"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "docker"
      - "infrastructure"
      - "automated"
