[build]
  # Build command for Next.js
  command = "npm run build"
  
  # Publish directory (Next.js static export)
  publish = "out"
  
  # Node.js version
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"

# Redirect rules for Next.js routing (SPA fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# API routes (disabled for static export)
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200

# Environment variables (these will be set in Netlify dashboard)
[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = ""
  NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
  SUPABASE_SERVICE_ROLE_KEY = ""
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = ""
  STRIPE_SECRET_KEY = ""
  STRIPE_WEBHOOK_SECRET = ""
  OPENAI_API_KEY = ""
  RESEND_API_KEY = ""
  NEXT_PUBLIC_APP_URL = ""
