import { Invoice } from '../../types/ui/dashboard';

export const mockInvoices: Invoice[] = [
  {
    id: "INV-2024-001",
    invoiceNumber: "2024-001",
    customerName: "ABC Bedrijf",
    customerEmail: "contact@abcbedrijf.nl",
    client: "ABC Bedrijf",
    description: "Website Ontwikkeling - Fase 1",
    amount: 2500,
    total: 3025,
    status: "paid",
    dueDate: "2024-02-15",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T15:30:00Z",
    items: [
      {
        id: "item-1",
        description: "Website Design - Responsive design en UI/UX",
        quantity: 1,
        price: 800,
        total: 800,
      },
      {
        id: "item-2",
        description: "Frontend Development - React/Next.js implementatie",
        quantity: 1,
        price: 1200,
        total: 1200,
      },
      {
        id: "item-3",
        description: "Backend Development - API en database setup",
        quantity: 1,
        price: 500,
        total: 500,
      },
    ],
    notes: "Project afgerond volgens planning",
    taxRate: 21,
    subtotal: 2500,
    taxAmount: 525,
  },
  {
    id: "INV-2024-002",
    invoiceNumber: "2024-002",
    customerName: "Maria Jansen",
    customerEmail: "maria@jansen.nl",
    client: "Maria Jansen",
    description: "Logo Design Project",
    amount: 450,
    total: 544.5,
    status: "paid",
    dueDate: "2024-01-25",
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-01-14T15:30:00Z",
    items: [
      {
        id: "item-4",
        description: "Logo Design - 3 concepten + 2 revisies",
        quantity: 1,
        price: 300,
        total: 300,
      },
      {
        id: "item-5",
        description: "Brand Guidelines - Kleuren en typografie",
        quantity: 1,
        price: 150,
        total: 150,
      },
    ],
    notes: "Design goedgekeurd",
    taxRate: 21,
    subtotal: 450,
    taxAmount: 94.5,
  },
  {
    id: "INV-2024-003",
    invoiceNumber: "2024-003",
    customerName: "TechStart",
    customerEmail: "info@techstart.nl",
    client: "TechStart",
    description: "E-commerce Platform Development",
    amount: 8500,
    total: 10285,
    status: "sent",
    dueDate: "2024-02-20",
    createdAt: "2024-01-20T10:00:00Z",
    updatedAt: "2024-01-20T10:00:00Z",
    items: [
      {
        id: "item-6",
        description: "Platform Development - Volledige e-commerce oplossing",
        quantity: 1,
        price: 6000,
        total: 6000,
      },
      {
        id: "item-7",
        description: "Payment Integration - Stripe en iDEAL integratie",
        quantity: 1,
        price: 1500,
        total: 1500,
      },
      {
        id: "item-8",
        description: "SEO Optimization - Zoekmachine optimalisatie",
        quantity: 1,
        price: 1000,
        total: 1000,
      },
    ],
    notes: "Project in uitvoering",
    taxRate: 21,
    subtotal: 8500,
    taxAmount: 1785,
  },
  {
    id: "INV-2024-004",
    invoiceNumber: "2024-004",
    customerName: "Local Bakery",
    customerEmail: "info@localbakery.nl",
    client: "Local Bakery",
    description: "Website Redesign",
    amount: 1000,
    total: 1210,
    status: "draft",
    dueDate: "2024-02-25",
    createdAt: "2024-01-25T10:00:00Z",
    updatedAt: "2024-01-25T10:00:00Z",
    items: [
      {
        id: "item-9",
        description: "Website Redesign - Moderne responsive website",
        quantity: 1,
        price: 800,
        total: 800,
      },
      {
        id: "item-10",
        description: "Content Management - CMS setup en training",
        quantity: 1,
        price: 200,
        total: 200,
      },
    ],
    notes: "Concept klaar voor review",
    taxRate: 21,
    subtotal: 1000,
    taxAmount: 210,
  },
  {
    id: "INV-2024-005",
    invoiceNumber: "2024-005",
    customerName: "Fitness Center",
    customerEmail: "admin@fitnesscenter.nl",
    client: "Fitness Center",
    description: "Mobile App Development",
    amount: 1500,
    total: 1815,
    status: "overdue",
    dueDate: "2024-01-20",
    createdAt: "2024-01-05T10:00:00Z",
    updatedAt: "2024-01-05T10:00:00Z",
    items: [
      {
        id: "item-11",
        description: "Mobile App - iOS en Android app",
        quantity: 1,
        price: 1200,
        total: 1200,
      },
      {
        id: "item-12",
        description: "Backend API - REST API voor app",
        quantity: 1,
        price: 300,
        total: 300,
      },
    ],
    notes: "Betaling achterstallig",
    taxRate: 21,
    subtotal: 1500,
    taxAmount: 315,
  },
  {
    id: "INV-2024-006",
    invoiceNumber: "2024-006",
    customerName: "Startup Inc",
    customerEmail: "contact@startupinc.nl",
    client: "Startup Inc",
    description: "Consulting Services",
    amount: 500,
    total: 605,
    status: "cancelled",
    dueDate: "2024-01-27",
    createdAt: "2024-01-12T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
    items: [
      {
        id: "item-13",
        description: "Business Consulting - Strategie en planning",
        quantity: 1,
        price: 400,
        total: 400,
      },
      {
        id: "item-14",
        description: "Market Research - Marktanalyse rapport",
        quantity: 1,
        price: 100,
        total: 100,
      },
    ],
    notes: "Project geannuleerd door klant",
    taxRate: 21,
    subtotal: 500,
    taxAmount: 105,
  },
  {
    id: "INV-2024-007",
    invoiceNumber: "2024-007",
    customerName: "Restaurant Group",
    customerEmail: "info@restaurantgroup.nl",
    client: "Restaurant Group",
    description: "Online Ordering System",
    amount: 2000,
    total: 2420,
    status: "sent",
    dueDate: "2024-02-18",
    createdAt: "2024-01-18T10:00:00Z",
    updatedAt: "2024-01-18T10:00:00Z",
    items: [
      {
        id: "item-15",
        description: "Ordering System - Online bestelsysteem",
        quantity: 1,
        price: 1500,
        total: 1500,
      },
      {
        id: "item-16",
        description: "Payment Gateway - Betaling integratie",
        quantity: 1,
        price: 500,
        total: 500,
      },
    ],
    notes: "Systeem live gegaan",
    taxRate: 21,
    subtotal: 2000,
    taxAmount: 420,
  },
  {
    id: "INV-2024-008",
    invoiceNumber: "2024-008",
    customerName: "Retail Chain",
    customerEmail: "it@retailchain.nl",
    client: "Retail Chain",
    description: "Inventory Management System",
    amount: 3000,
    total: 3630,
    status: "paid",
    dueDate: "2024-02-08",
    createdAt: "2024-01-08T10:00:00Z",
    updatedAt: "2024-01-12T15:30:00Z",
    items: [
      {
        id: "item-17",
        description: "Inventory System - Voorraadbeheer systeem",
        quantity: 1,
        price: 2000,
        total: 2000,
      },
      {
        id: "item-18",
        description: "Reporting Dashboard - Rapportage dashboard",
        quantity: 1,
        price: 1000,
        total: 1000,
      },
    ],
    notes: "Implementatie succesvol",
    taxRate: 21,
    subtotal: 3000,
    taxAmount: 630,
  },
];

export function getInvoicesStats() {
  const total = mockInvoices.length;
  const paid = mockInvoices.filter((i) => i.status === "paid").length;
  const pending = mockInvoices.filter((i) => i.status === "sent").length;
  const overdue = mockInvoices.filter((i) => i.status === "overdue").length;
  const draft = mockInvoices.filter((i) => i.status === "draft").length;
  const cancelled = mockInvoices.filter((i) => i.status === "cancelled").length;

  const totalRevenue = mockInvoices
    .filter((i) => i.status === "paid")
    .reduce((sum, i) => sum + (i.total || 0), 0);

  const avgInvoiceValue = paid > 0 ? totalRevenue / paid : 0;

  return {
    total,
    paid,
    pending,
    overdue,
    draft,
    cancelled,
    totalRevenue,
    avgInvoiceValue,
  };
}