name: 🚀 AI-Powered Deployment

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Allow manual deployment

env:
  NODE_VERSION: '18'
  REGISTRY: ghcr.io

jobs:
  # Build and test before deployment
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
      image-digest: ${{ steps.build.outputs.digest }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Type checking
      run: npm run type-check

    - name: Run tests
      run: npm run test:run

    - name: ESLint analysis
      run: npm run lint

    - name: Build application
      run: npm run build
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v5
      with:
        name: nextjs-build
        path: .next/
        retention-days: 7

  # Deploy to Hugging Face Spaces
  deploy-huggingface:
    name: Deploy to Hugging Face Spaces
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: nextjs-build
        path: .next/

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --production

    - name: Deploy to Hugging Face Spaces
      run: |
        echo "Deploying to Hugging Face Spaces..."
        # Using Hugging Face Spaces Git-based deployment
        # The repository is automatically deployed when pushed to main branch

    - name: Health check
      run: |
        echo "✅ Deployment completed successfully"
        echo "🌐 Application will be available at: https://huggingface.co/spaces/${{ github.repository }}"

  # Deploy to Netlify (Alternative)
  deploy-netlify:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'workflow_dispatch' || (github.ref == 'refs/heads/develop' && github.event_name == 'push')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build for Netlify
      run: npm run build
      env:
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v3
      with:
        publish-dir: '.next'
        production-deploy: ${{ github.ref == 'refs/heads/main' }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deployed from GitHub Actions"
        enable-pull-request-comment: true
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  # Notify on deployment status
  notify-deployment:
    name: Deployment Notification
    runs-on: ubuntu-latest
    needs: [deploy-huggingface, deploy-netlify]
    if: always()

    steps:
    - name: Deployment Status Summary
      run: |
        echo "## 🚀 Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ "${{ needs.deploy-huggingface.result }}" == "success" ]; then
          echo "✅ **Hugging Face Spaces**: Deployed successfully" >> $GITHUB_STEP_SUMMARY
          echo "🌐 **URL**: https://huggingface.co/spaces/${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
        fi
        if [ "${{ needs.deploy-netlify.result }}" == "success" ]; then
          echo "✅ **Netlify**: Deployed successfully" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📊 Build Information" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Trigger**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
